### PR TITLE
Dynamic rate control

### PR DESCRIPTION
**Pull request by athairus**

### CODE REVIEW

**Comment by Druage** [comment]
Does this actually work?

**Comment by athairus** [comment]
Yes! Still crackles a lot, but the code works and the output buffer holds steady at around 50% full.

**Comment by Druage** [comment]
Hmmm. Maybe the audio has aliasing on it. I know that causes sharp spikes that could be pops. Or maybe there is some other bug in it. I'll try it out once I get a change to download it.

**Comment by Druage** [comment]
What OS are you testing this on?

**Comment by athairus** [comment]
OS X, Windows. Both have some cracks and pops. They also occasionally have some LOUD static for an instant.

**Comment by Druage** [comment]
I used to get this with the libsoxr resampler as well. I'm not too sure what the issue is. Maybe out the audio buffer through an audio visualizer to see what the pop is.

**Comment by athairus** [comment]
The important takeaway is that the output buffer is always around half-full, never underrunning, but it still crackles. Something else outside of Audio is the issue.

**Pull request merged**
