### PR TITLE
Use temporary directory for unpacking zips on-demand

### LINKED ISSUE #190: Can't launch games that are zipped
I dragged a folder with a zip into Phoenix, then tried to run the zip.  Note that Phoenix found the artwork for the game so that seems to be correct, but the code that launches the game doesn't handle zip correctly at the moment:

Log:

```
Debugging starts
QML debugging is enabled. Only use this in a safe environment.
phoenix.library: Portable mode
phoenix.library: Opening library database /Users/jgauci/github/build-phoenix-Desktop_Qt_5_5_0_clang_64bit-Debug/frontend/Phoenix.app/Contents/MacOS/Metadata/systems.sqlite
phoenix.library: Opening library database /Users/jgauci/github/build-phoenix-Desktop_Qt_5_5_0_clang_64bit-Debug/frontend/Phoenix.app/Contents/MacOS/Metadata/openvgdb.sqlite
QML Debugger: Waiting for connection on port 58208...
phoenix.library: Opening library database /Users/jgauci/github/build-phoenix-Desktop_Qt_5_5_0_clang_64bit-Debug/frontend/Phoenix.app/Contents/MacOS/User Data/gamelibrary.sqlite
phoenix.input: Opening custom controller DB file: /Users/jgauci/github/build-phoenix-Desktop_Qt_5_5_0_clang_64bit-Debug/frontend/Phoenix.app/Contents/MacOS/User Data/gamecontrollerdb.txt
phoenix.input: Loaded custom controller DB successfully.
phoenix.library: mWorkerThread Started...
void Library::GameFileInfo::prepareMetadata() "1033EBA4"
phoenix.library: Worker Started...
ImportData:  "Super Nintendo" "zip:///Volumes/pawn/Roms/No-Intro/Nintendo - Super Nintendo Entertainment System/Mega Man X (USA).zip<><>Mega Man X (USA).sfc" "http://img.gamefaqs.net/box/7/2/8/19728_front.jpg"
qt.network.ssl: QSslSocket: cannot resolve SSL_set_psk_client_callback
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_server_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_server_method
qt.network.ssl: QSslSocket: cannot resolve SSL_select_next_proto
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
phoenix.library: Worker Finished...
phoenix.library: "/Volumes/pawn/Roms/No-Intro/Nintendo - Super Nintendo Entertainment System/Mega Man X (USA).sfc"  does not exist. Launch will fail...
```

### PR DESCRIPTION
**Pull request by MisterTea**
Fixes #190

### CODE REVIEW

**Comment by athairus** [comment]
This is missing a few things we need:
- Check if the file already exists
- Put temp files under `Phoenix` folder

**Comment by MisterTea** [comment]
@athairus Please don't put temp files under the pheonix folder.  This will make you responsible for cleaning them up.  The OS does a great job of cleaning up the /tmp folder already.

**Comment by athairus** [comment]
I meant within the temp folder.

`/tmp/Phoenix`, for example.

**Comment by MisterTea** [comment]
Gotcha, sure you can append anything you want after that temp directory

**Comment by athairus** [comment]
These changes were merged in https://github.com/team-phoenix/Phoenix/commit/91a4942f6fc29b34bbb09ab200f07cde7c061853, but no one closed the PR!

**Pull request closed without merging**
